on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        ls
    - name: connect pull build deploy
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i /.ssh/id_rsa "cd ${{ secrets.WORK_DIR }} && sudo git checkout ${{ secrets.MAIN_BRANCH }} && sudo git pull && sudo npm i && sudo npm run build && sudo mv /dist/* ../www/html/"
    - name: cleanup
      run: rm -rf ~/.ssh
